# Generated by Django 5.0.3 on 2024-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_code', models.CharField(max_length=100)),
                ('principal', models.CharField(max_length=100)),
                ('total_students', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('std', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
